version: '3.8' # Specify the Docker Compose file format version
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home_data:/var/jenkins_home # Persist Jenkins data (configs, plugins, jobs)
    networks:
      - net # Define a custom Docker network
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      context: . # Define the build context ('Dockerfile' should be inside the 'centos7' directory)
    networks:
      - net

networks:
  net: # Define a custom Docker network to enable communication between containers

volumes:
  jenkins_home_data: # Define a persistent volume for Jenkins data storage
